name: pcagent
channels:
  - defaults
dependencies:
  - python=3.10.14
  - aiofiles=22.1.0
  - blas=1.0=mkl
  - blinker=1.6.2
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - click=8.1.7
  - colorama=0.4.6
  - flask=3.0.3
  - intel-openmp=2023.1.0
  - itsdangerous=2.2.0
  - jinja2=3.1.4
  - libffi=3.4.4
  - libiconv=1.16
  - libxml2=2.10.4
  - libxslt=1.1.37
  - lxml=5.2.1
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.14
  - pip=24.0
  - setuptools=69.5.1
  - sortedcontainers=2.4.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tzdata=2024a
  - vc=14.2
  - vs2015_runtime=14.29.30133
  - werkzeug=3.0.3
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - altgraph==0.17.4
      - annotated-types==0.7.0
      - anyio==4.4.0
      - astor==0.8.1
      - async-timeout==4.0.3
      - attrs==24.2.0
      - beautifulsoup4==4.12.3
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - comtypes==1.4.5
      - contourpy==1.3.0
      - customtkinter==5.2.2
      - cycler==0.12.1
      - cython==3.0.11
      - darkdetect==0.8.0
      - dashscope==1.20.9
      - decorator==5.1.1
      - distro==1.9.0
      - exceptiongroup==1.2.2
      - fire==0.7.0
      - fonttools==4.54.1
      - frozenlist==1.4.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.2
      - idna==3.8
      - imageio==2.35.1
      - imgaug==0.4.0
      - jiter==0.5.0
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lmdb==1.5.1
      - matplotlib==3.9.2
      - mouseinfo==0.1.3
      - multidict==6.1.0
      - networkx==3.3
      - openai==1.44.1
      - opencv-contrib-python==4.10.0.84
      - opencv-python==4.10.0.84
      - opt-einsum==3.3.0
      - packaging==24.1
      - paddleocr==2.8.1
      - paddlepaddle==2.6.2
      - pefile==2023.2.7
      - pillow==10.4.0
      - protobuf==3.20.2
      - psutil==6.1.0
      - pyautogui==0.9.54
      - pyclipper==1.3.0.post5
      - pydantic==2.9.1
      - pydantic-core==2.23.3
      - pygetwindow==0.0.9
      - pyinstaller==6.9.0
      - pyinstaller-hooks-contrib==2024.7
      - pymsgbox==1.0.9
      - pynput==1.7.7
      - pyparsing==3.1.4
      - pyperclip==1.9.0
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.15.0
      - pyrect==0.2.0
      - pyscreeze==0.1.30
      - python-dateutil==2.9.0.post0
      - python-docx==1.1.2
      - pytweening==1.2.0
      - pywin32==306
      - pywin32-ctypes==0.2.2
      - pywinauto==0.6.8
      - pyyaml==6.0.2
      - rapidfuzz==3.10.0
      - requests==2.32.3
      - scikit-image==0.24.0
      - scipy==1.14.1
      - shapely==2.0.6
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - termcolor==2.4.0
      - tifffile==2024.9.20
      - tqdm==4.66.5
      - typing-extensions==4.12.2
      - urllib3==2.2.2
      - websocket-client==1.8.0
      - wmi==1.5.1
      - yarl==1.11.1