### model
model_name_or_path: Qwen/Qwen2-VL-72B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json
freeze_vision_tower: true

### dataset
dataset: agent
template: qwen2_vl
cutoff_len: 8192
overwrite_cache: true
preprocessing_num_workers: 64

### output
output_dir: /nas/shared/GAIR/yhhe/pc-agent/Qwen2-VL-72B-Instruct-sft
logging_steps: 1
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-6
num_train_epochs: 2
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000
